name: Build and Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      ZKSYNC_ERA_MAINNET_RPC: ${{ secrets.ZKSYNC_ERA_MAINNET_RPC }}
      ETH_MAINNET_RPC: ${{ secrets.ETH_MAINNET_RPC }}
    steps:
      - name: 🧾 Checkout repository
        uses: actions/checkout@v3

      - name: ❄️ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: 🍞 Install dependencies
        run: npm install

      - name: Compile contracts (Hardhat)
        run: |
          node --loader ts-node/esm node_modules/hardhat/internal/cli/cli.js compile

      - name: 🧱 Build frontend
        run: |
          cd frontend
          npm install
          npm run build
      
      - name: 🔍 Run ESLint
        run: npm run lint
        working-directory: frontend

